# Generated by Django 3.2.5 on 2022-06-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfprep', '0002_region_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='minor_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_prod', to='drfprep.product'),
        ),
    ]
